site_name: Kura
site_url: https://usekura.xyz
site_description: A tool for analysing and visualising chat data

extra:
  analytics:
    provider: google
    property: G-5ZYBS2C5VF

theme:
  name: material
  features:
    - content.code.select
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - API Reference: api/index.md
  - Blog: 
    - blog/index.md

plugins:
  - blog
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      use_git: false
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../kura]
          options:
            docstring_style: google
            show_root_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            members_order: source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true