version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    restart: unless-stopped
    environment:
      - KURA_CHECKPOINT_DIR=/checkpoints
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./kura_explorer.db}
    volumes:
      - ${KURA_CHECKPOINT_DIR}:/checkpoints:ro
      - ./data:/app/data
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--workers", "4"]

  frontend:
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    profiles:
      - []  # Always run in production