name: Import Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run import benchmark
      env:
        OPENAI_API_KEY: sk-mock-key-for-testing
      run: |
        uv run python -c "
        import time
        import sys
        
        print('=== Kura Import Benchmark ===')
        print(f'Python version: {sys.version}')
        print()
        
        # Benchmark kura.types import
        start_time = time.perf_counter()
        try:
            import kura.types
            types_time = time.perf_counter() - start_time
            print(f'✓ kura.types import: {types_time:.4f}s')
        except Exception as e:
            print(f'✗ kura.types import failed: {e}')
            types_time = 0
        
        # Benchmark kura import
        start_time = time.perf_counter()
        try:
            import kura
            kura_time = time.perf_counter() - start_time
            print(f'✓ kura import: {kura_time:.4f}s')
        except Exception as e:
            print(f'✗ kura import failed: {e}')
            kura_time = 0
        
        total_time = types_time + kura_time
        print()
        print(f'Total import time: {total_time:.4f}s')
        print('========================')
        "
        
