name: Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyright
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pyright
        run: pyright

      # Optional: Upload Pyright results as an artifact
      - name: Upload Pyright results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pyright-results
          path: pyrightconfig.json
